runtime: python39
entrypoint: ./run.sh $PORT

handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  DJANGO_ENV: prod
  DJANGO_SETTINGS_MODULE: zosia16.settings.prod
  PYTHONUNBUFFERED: 1
